import './globals.css';
import Link from 'next/link';

export const metadata = {
    title: 'PRP',
    description: 'Generated by prp',
};

export default async function RootLayout({ children }) {
    const res = await fetch('http://localhost:9999/topics', { next: { revalidate: 0 } });
    const topics = await res.json();
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {topics.map((v) => {
                        return (
                            <li key={v.id}>
                                <Link href={`/read/${v.id}`}>{v.title}</Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">Create</Link>
                    </li>
                    <li>
                        <Link href="/update/1">Update</Link>
                    </li>
                    <li>
                        <input type="button" value="delete" />
                    </li>
                </ul>
            </body>
        </html>
    );
}
